// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/story-structure/stc_beat.proto

package storystructurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the beat to retrieve.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBeatRequest) Reset() {
	*x = GetBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeatRequest) ProtoMessage() {}

func (x *GetBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeatRequest.ProtoReflect.Descriptor instead.
func (*GetBeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{0}
}

func (x *GetBeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ids of the beats to retrieve. A maximum number of ids that can be provided in one request may be
	// defined by the server.
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListBeatsRequest) Reset() {
	*x = ListBeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeatsRequest) ProtoMessage() {}

func (x *ListBeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeatsRequest.ProtoReflect.Descriptor instead.
func (*ListBeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{1}
}

func (x *ListBeatsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type SearchBeatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Batch size for the search. The server may cap this value.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset for the search. The server may cap this value.
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *SearchBeatsRequest) Reset() {
	*x = SearchBeatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBeatsRequest) ProtoMessage() {}

func (x *SearchBeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBeatsRequest.ProtoReflect.Descriptor instead.
func (*SearchBeatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{2}
}

func (x *SearchBeatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchBeatsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the beat to create. While not required to be unique, it is recommended to be, so it is not
	// confused with other beats.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The main prompt that should be used to generate a story with this beat.
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *CreateBeatRequest) Reset() {
	*x = CreateBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeatRequest) ProtoMessage() {}

func (x *CreateBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeatRequest.ProtoReflect.Descriptor instead.
func (*CreateBeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBeatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type UpdateBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the existing beat to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the beat to create. While not required to be unique, it is recommended to be, so it is not
	// confused with other beats.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The main prompt that should be used to generate a story with this beat.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *UpdateBeatRequest) Reset() {
	*x = UpdateBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBeatRequest) ProtoMessage() {}

func (x *UpdateBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBeatRequest.ProtoReflect.Descriptor instead.
func (*UpdateBeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBeatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type DeleteBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the beat to delete.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBeatRequest) Reset() {
	*x = DeleteBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeatRequest) ProtoMessage() {}

func (x *DeleteBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeatRequest.ProtoReflect.Descriptor instead.
func (*DeleteBeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListBeatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The beats that were retrieved.
	Beats []*Beat `protobuf:"bytes,1,rep,name=beats,proto3" json:"beats,omitempty"`
}

func (x *ListBeatsResponse) Reset() {
	*x = ListBeatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBeatsResponse) ProtoMessage() {}

func (x *ListBeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBeatsResponse.ProtoReflect.Descriptor instead.
func (*ListBeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{6}
}

func (x *ListBeatsResponse) GetBeats() []*Beat {
	if x != nil {
		return x.Beats
	}
	return nil
}

type SearchBeatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ids of the beats matching the search. Details for each beat can be retrieved using ListBeats,
	// or separately using GetBeat.
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *SearchBeatsResponse) Reset() {
	*x = SearchBeatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBeatsResponse) ProtoMessage() {}

func (x *SearchBeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBeatsResponse.ProtoReflect.Descriptor instead.
func (*SearchBeatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{7}
}

func (x *SearchBeatsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Beat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique identifier of the beat.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// THe display name of the beat.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The prompt that should be used to generate a story with this beat.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *Beat) Reset() {
	*x = Beat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_story_structure_stc_beat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beat) ProtoMessage() {}

func (x *Beat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_structure_stc_beat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beat.ProtoReflect.Descriptor instead.
func (*Beat) Descriptor() ([]byte, []int) {
	return file_proto_story_structure_stc_beat_proto_rawDescGZIP(), []int{8}
}

func (x *Beat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Beat) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

var File_proto_story_structure_stc_beat_proto protoreflect.FileDescriptor

var file_proto_story_structure_stc_beat_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x73, 0x74, 0x63, 0x5f, 0x62, 0x65, 0x61, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x42, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x3f, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x4f, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x23, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x3a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x62, 0x65, 0x61, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x52, 0x05, 0x62, 0x65, 0x61, 0x74, 0x73, 0x22, 0x27, 0x0a,
	0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x04, 0x42, 0x65, 0x61, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x32, 0xa4, 0x03, 0x0a, 0x0b, 0x42,
	0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x65, 0x61,
	0x74, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x61, 0x74, 0x73,
	0x12, 0x1b, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a,
	0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65, 0x61, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42,
	0x65, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x65,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x65, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0a, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x2b, 0x5a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x2d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x3b, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_story_structure_stc_beat_proto_rawDescOnce sync.Once
	file_proto_story_structure_stc_beat_proto_rawDescData = file_proto_story_structure_stc_beat_proto_rawDesc
)

func file_proto_story_structure_stc_beat_proto_rawDescGZIP() []byte {
	file_proto_story_structure_stc_beat_proto_rawDescOnce.Do(func() {
		file_proto_story_structure_stc_beat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_story_structure_stc_beat_proto_rawDescData)
	})
	return file_proto_story_structure_stc_beat_proto_rawDescData
}

var file_proto_story_structure_stc_beat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_story_structure_stc_beat_proto_goTypes = []any{
	(*GetBeatRequest)(nil),      // 0: structure.GetBeatRequest
	(*ListBeatsRequest)(nil),    // 1: structure.ListBeatsRequest
	(*SearchBeatsRequest)(nil),  // 2: structure.SearchBeatsRequest
	(*CreateBeatRequest)(nil),   // 3: structure.CreateBeatRequest
	(*UpdateBeatRequest)(nil),   // 4: structure.UpdateBeatRequest
	(*DeleteBeatRequest)(nil),   // 5: structure.DeleteBeatRequest
	(*ListBeatsResponse)(nil),   // 6: structure.ListBeatsResponse
	(*SearchBeatsResponse)(nil), // 7: structure.SearchBeatsResponse
	(*Beat)(nil),                // 8: structure.Beat
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_proto_story_structure_stc_beat_proto_depIdxs = []int32{
	8, // 0: structure.ListBeatsResponse.beats:type_name -> structure.Beat
	0, // 1: structure.BeatService.GetBeat:input_type -> structure.GetBeatRequest
	1, // 2: structure.BeatService.ListBeats:input_type -> structure.ListBeatsRequest
	2, // 3: structure.BeatService.SearchBeats:input_type -> structure.SearchBeatsRequest
	3, // 4: structure.BeatService.CreateBeat:input_type -> structure.CreateBeatRequest
	4, // 5: structure.BeatService.UpdateBeat:input_type -> structure.UpdateBeatRequest
	5, // 6: structure.BeatService.DeleteBeat:input_type -> structure.DeleteBeatRequest
	8, // 7: structure.BeatService.GetBeat:output_type -> structure.Beat
	6, // 8: structure.BeatService.ListBeats:output_type -> structure.ListBeatsResponse
	7, // 9: structure.BeatService.SearchBeats:output_type -> structure.SearchBeatsResponse
	8, // 10: structure.BeatService.CreateBeat:output_type -> structure.Beat
	8, // 11: structure.BeatService.UpdateBeat:output_type -> structure.Beat
	9, // 12: structure.BeatService.DeleteBeat:output_type -> google.protobuf.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_story_structure_stc_beat_proto_init() }
func file_proto_story_structure_stc_beat_proto_init() {
	if File_proto_story_structure_stc_beat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_story_structure_stc_beat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListBeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SearchBeatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListBeatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SearchBeatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_story_structure_stc_beat_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Beat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_story_structure_stc_beat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_story_structure_stc_beat_proto_goTypes,
		DependencyIndexes: file_proto_story_structure_stc_beat_proto_depIdxs,
		MessageInfos:      file_proto_story_structure_stc_beat_proto_msgTypes,
	}.Build()
	File_proto_story_structure_stc_beat_proto = out.File
	file_proto_story_structure_stc_beat_proto_rawDesc = nil
	file_proto_story_structure_stc_beat_proto_goTypes = nil
	file_proto_story_structure_stc_beat_proto_depIdxs = nil
}
